# Base configs
baseurl: "https://semeer.in/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Photography by Semeer"
subtitle: "My Collection"
author: "Semeer"
header:
 title: "Photography"
 subtitle: "by Semeer"
footer:
 name: "Semeer P A"
 bio: "#"
 github: "#"
web_design: "#"
social_urls:
  facebook: "https://www.facebook.com/semeer.in"
  twitter: "https://twitter.com/semeer_in"
  instagram: "https://www.instagram.com/semeer.in"
  dribbble: "https://dribbble.com/bizmoz"
  linkedin: "https://www.linkedin.com/semeer-in"
  github: "https://github.com/bizmoz"

theme: jekyll-theme-slate