# Base configs
baseurl: "https://semeer.in/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Photography by Semeer"
subtitle: "My Collection"
author: "Semeer"
header:
 title: "Photography"
 subtitle: "by Semeer"
footer:
 name: "#"
 bio: "#"
 github: "#"
web_design: "#"
social_urls:
  facebook: "#"
  twitter: "#"
  instagram: "#"
  dribbble: "#"
  linkedin: "#"
  github: "#"

theme: jekyll-theme-slate